version: '3.5'

services:

  api:
    build: .
    env_file:
      - .env
    volumes:
      - ./server:/app/server
      - ./server.js:/app/server.js
    ports:
      - "5001:5001"
    networks:
      - twitternet

networks:
  twitternet:
    external:
      name: leggo_twitter_network
